export default class getNames {
    names: string[];
    getCalled: number;
    arrLenght: number;
    index: any;
    constructor(arr) {
        this.names = [
            ' thousand',
            ' million',
            ' billion',
            ' trillion',
            ' quadrillion',
            ' quintillion',
            ' sextillion',
            ' septillion',
            ' octillion',
            ' nonillion',
            ' decillion',
            ' undecillion',
            ' doudecillion',
            ' tredecillion',
            ' quattuordecillion',
            ' quindecillion',
            ' sexdecillion',
            ' octodecillion',
            ' novemdecillion',
            ' vigitillion',
            ' unvigintillion',
            ' duovigintillion',
            ' trevigintillion',
            ' quattuorvigintillion',
            ' quinvigintillion',
            ' sexvigintillion',
            ' septenvigintillion',
            ' octavigintillion',
            ' novemvigintillion',
            ' trigintillion',
            ' untrigintillion',
            ' googol',
            ' tretrigintillion',
            ' quattuortrigintillion',
            ' quintrigintillion',
            ' sextrigintillion',
            ' septentrigintillion',
            ' octatrigintillion',
            ' novemtrigintillion',
            ' quadragintillion',
            ' unquadragintillion',
            ' duoquadragintillion',
            ' trequadragintillion',
            ' quattuorquadragintillion',
            ' quinquadragintillion',
            ' sexquadragintillion',
            ' septenquadragintillion',
            ' octaquadragintillion',
            ' novemquadragintillion',
            ' unquinquagintillion',
            ' duoquinquagintillion',
            ' trequinquagintillion',
            ' quattuorquinquagintillion',
            ' quinquinquagintillion',
            ' sexquinquagintillion',
            ' septenquinquagintillion',
            ' octaquinquagintillion',
            ' novemquinquagintillion',
            ' unsexagintillion',
            ' duosexagintillion',
            ' tresexagintillion',
            ' quattuorsexagintillion',
            ' quinsexagintillion',
            ' sexsexagintillion',
            ' septensexagintillion',
            ' octasexagintillion',
            ' novemsexagintillion',
            ' unseptuagintillion',
            ' duoseptuagintillion',
            ' treseptuagintillion',
            ' quattuorseptuagintillion',
            ' quinseptuagintillion',
            ' sexseptuagintillion',
            ' septenseptuagintillion',
            ' octaseptuagintillion',
            ' novemseptuagintillion',
            ' unoctogintillion',
            ' duooctogintillion',
            ' treoctogintillion',
            ' quattuoroctogintillion',
            ' quinoctogintillion',
            ' sexoctogintillion',
            ' septenoctogintillion',
            ' octaoctogintillion',
            ' novemoctogintillion',
            ' unnonagintillion',
            ' duononagintillion',
            ' trenonagintillion',
            ' quattuornonagintillion',
            ' quinnonagintillion',
            ' sexnonagintillion',
            ' septennonagintillion',
            ' octanonagintillion',
            ' novemnonagintillion'];
        this.getCalled = 0;
        this.arrLenght = arr.length - 1;
        this.index = this.arrLenght;
    }
    get() {
        this.getCalled++;
        if (this.getCalled === (this.arrLenght + 1)) {
            return undefined;
        }
        this.index--;
        return this.names[this.index];
    }
}